# Generated by Django 5.2.5 on 2025-10-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleModel',
            new_name='Book',
        ),
    ]
